server:
  port: 8081

spring:
  application:
    name: my_stall
  profiles:
    active: dev
# mybatis-plus??
mybatis-plus:
  mapper-locations: classpath*:mapper/*/*/*.xml
  typeAliasesPackage: com.mystall.*.entity,com.mystall.*.*.entity